### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by Klimpzz** [chrillux/brottsplatskartan#1]
Hello.
How do i specify the area in HA?
I have this in my configuration.yaml 
sensor:
  - platform: brottsplatskartan
    name: "Brott på Gotland"
    area: "Gotlands län"

And getting this 
Unable to read file /home/homeassistant/.homeassistant/configuration.yaml: 'utf-8' codec can't decode byte 0xe5 in position 7368: invalid continuation byte

What is the "Right" way to write it?
sorry for dumb questions.

**Comment by chrillux** [comment]
Hello!

I thought I was watching this repo but I was not, so I haven't seen this message until now. :)

I don't know if you fixed it already but that "should" work. 

I tried your config and it worked for me liked this:
```
sensor:
  - platform: brottsplatskartan
    name: "Brott på Gotland"
    area: "Gotlands län"
```
If that snippet won't work for you then I don't know. It looks like Home Assistant was not able to read you configuration yaml for reasons that are pretty specific to your installation.

Christian
